image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "manojs97" -p "RH83eDfCWDdibYgpRQ5N" registry.gitlab.com

build-master:
  stage: build
  script:
    - docker images
    - docker build -t registry.gitlab.com/manojs97/hello-node:v1 .
    - docker images
    - docker push registry.gitlab.com/manojs97/hello-node:v1
deploy-stage:
   stage: deploy
   script:
    - docker images
    - docker pull registry.gitlab.com/manojs97/hello-node:v1	
    - docker images
    - docker run -p 8080:8080 -itd registry.gitlab.com/manojs97/hello-node:v1
    - docker ps


