apiVersion: v1
kind: Secret
metadata:
  name: mysec
  namespace: elk
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJBdXRoIjogImJXRnViMnB6T1RjNlRXRnViMnBBT1RjPSIsCiAgICAgICJFbWFpbCI6ICJtYW5vai5zdXJ1ZHdhZEBjb3Jpb2xpcy5jby5pbiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
